export const brandsMap = [
  { buttonText: `annabelle`, buttonValueText: "annabelle" },
  { buttonText: `benefit`, buttonValueText: "benefit" },
  { buttonText: `boosh`, buttonValueText: "boosh" },
  { buttonText: `almay`, buttonValueText: "almay" },
  { buttonText: `alva`, buttonValueText: "alva" },
  { buttonText: `clinique`, buttonValueText: "clinique" },
  { buttonText: `covergirl`, buttonValueText: "covergirl" },
  {
    buttonText: `coastal classic creation`,
    buttonValueText: "coastal classic creation",
  },
  { buttonText: `colourpop`, buttonValueText: "colourpop" },
  { buttonText: `dalish`, buttonValueText: "dalish" },
  { buttonText: `dior`, buttonValueText: "dior" },
  { buttonText: `dr.hauschka`, buttonValueText: "dr.hauschka" },
  { buttonText: `e.l.f.`, buttonValueText: "e.l.f." },
  { buttonText: `iman`, buttonValueText: "iman" },
  { buttonText: `l'oreal`, buttonValueText: "l'oreal" },
  { buttonText: `marcelle`, buttonValueText: "marcelle" },
  { buttonText: `maybelline`, buttonValueText: "maybelline" },
  { buttonText: `milani`, buttonValueText: "milani" },
  { buttonText: `mineral fusion`, buttonValueText: "mineral fusion" },
  { buttonText: `misa`, buttonValueText: "misa" },
  { buttonText: `mistura`, buttonValueText: "mistura" },
  { buttonText: `moov`, buttonValueText: "moov" },
  { buttonText: `nudus`, buttonValueText: "nudus" },
  { buttonText: `nyx`, buttonValueText: "nyx" },
  { buttonText: `revion`, buttonValueText: "revion" },
  { buttonText: `salon perfect`, buttonValueText: "salon perfect" },
  { buttonText: `sante`, buttonValueText: "sante" },
  { buttonText: `sinful colours`, buttonValueText: "sinful colours" },
  { buttonText: `smashbox`, buttonValueText: "smashbox" },
  { buttonText: `stila`, buttonValueText: "stila" },
  { buttonText: `suncoat`, buttonValueText: "suncoat" },
  { buttonText: `w3llpeople`, buttonValueText: "w3llpeople" },
  { buttonText: `wet n wild`, buttonValueText: "wet n wild" },
  { buttonText: `zorah`, buttonValueText: "zorah" },
];
