export const BrandsMap = [
  //Brand Catgory Map Array Values//
  "annabelle",
  "benefit",
  "boosh",
  "almay",
  "alva",
  "clinique",
  "covergirl",
  "coastal classic creation",
  "colourpop",
  "covergirl",
  "dalish",
  "dior",
  "dr.hauschka",
  "e.l.f.",
  "iman",
  "l'oreal",
  "marcelle",
  "maybelline",
  "milani",
  "mineral fusion",
  "misa",
  "mistura",
  "moov",
  "nudus",
  "nyx",
  "orly",
  "pacifica",
  "penny lane organics",
  "physicans formula",
  "piggy paint",
  "pure anada",
  "rejuva minerals",
  "revion",
  "salon perfect",
  "sante",
  "sinful colours",
  "smashbox",
  "stila",
  "suncoat",
  "w3llpeople",
  "wet n wild",
  "zorah",
];
