export const NavigationButtonMap = [
  {
    NavText: "Makeup",
    href: "content/makeup",
    ariaLabel: "Makeup Nav Button",
    ButtonColor: "#9400D3",
    ButtonType: false,
    arraylist: [
      { buttonText: `annabelle`, buttonValueText: "annabelle" },
      { buttonText: `benefit`, buttonValueText: "benefit" },
      { buttonText: `boosh`, buttonValueText: "boosh" },
      { buttonText: `almay`, buttonValueText: "almay" },
      { buttonText: `alva`, buttonValueText: "alva" },
      { buttonText: `clinique`, buttonValueText: "clinique" },
      { buttonText: `covergirl`, buttonValueText: "covergirl" },
    ],
  },
  {
    NavText: "Brands",
    href: "content/brands",
    ariaLabel: "Brands supported by site nav button",
    ButtonColor: "#FF7F00",
    ButtonType: true,
    arraylist: [
      { buttonText: `annabelle`, buttonValueText: "annabelle" },
      { buttonText: `benefit`, buttonValueText: "benefit" },
      { buttonText: `boosh`, buttonValueText: "boosh" },
      { buttonText: `almay`, buttonValueText: "almay" },
      { buttonText: `alva`, buttonValueText: "alva" },
      { buttonText: `clinique`, buttonValueText: "clinique" },
      { buttonText: `covergirl`, buttonValueText: "covergirl" },
      {
        buttonText: `coastal classic creation`,
        buttonValueText: "coastal classic creation",
      },
      { buttonText: `colourpop`, buttonValueText: "colourpop" },
      { buttonText: `dalish`, buttonValueText: "dalish" },
      { buttonText: `dior`, buttonValueText: "dior" },
      { buttonText: `dr.hauschka`, buttonValueText: "dr.hauschka" },
      { buttonText: `e.l.f.`, buttonValueText: "e.l.f." },
      { buttonText: `iman`, buttonValueText: "iman" },
      { buttonText: `l'oreal`, buttonValueText: "l'oreal" },
      { buttonText: `marcelle`, buttonValueText: "marcelle" },
      { buttonText: `maybelline`, buttonValueText: "maybelline" },
      { buttonText: `milani`, buttonValueText: "milani" },
      { buttonText: `mineral fusion`, buttonValueText: "mineral fusion" },
      { buttonText: `misa`, buttonValueText: "misa" },
    ],
  },
];
