export const SideMenuMainMenuButtonMap = [
  {
    IconPicturePrefix: "fa-solid",
    IconPicture: "fa-building-columns",
    IconArrowPreFix: "fa-solid",
    IconArrow: "fa-arrow-right-from-bracket",
    ButtonText: "Theme Menu",
    ThemeSetting: "true",
    MusicSetting: "false",
    NavSetting: "false",
    MainMenu: "themeMenu",
    MenuButtonType: "ThemeMenuButton",
  },
  {
    IconPicturePrefix: "fa-solid",
    IconPicture: "fa-music",
    IconArrowPreFix: "fa-solid",
    IconArrow: "fa-arrow-right-from-bracket",
    ButtonText: "Music Menu",
    MusicSetting: "true",
    ThemeSetting: "false",
    NavSetting: "false",
    MainMenu: "defaultMenu",
    MenuButtonType: "ThemeMenuButton",
  },
  {
    IconPicturePrefix: "fa-solid",
    IconPicture: "fa-circle-user",
    IconArrowPreFix: "fa-solid",
    IconArrow: "fa-arrow-right-from-bracket",
    ButtonText: "Sign In",
    SignInSetting: "true",
    ThemeSetting: "false",
    MusicSetting: "false",
    NavSetting: "false",
    MainMenu: "adminMenu",
    MenuButtonType: "ThemeMenuButton",
  },

  {
    IconPicturePrefix: "fa-solid",
    IconPicture: "fa-circle-user",
    IconArrowPreFix: "fa-solid",
    IconArrow: "fa-arrow-right-from-bracket",
    ButtonText: "Moblie Nav Menu",
    SignInSetting: "false",
    ThemeSetting: "false",
    MusicSetting: "false",
    NavSetting: "true",
    MainMenu: "adminMenu",
    MenuButtonType: "moblieMenuButton",
  },
];
