export const ContentSideBarButtonMap = [
  {
    asideTextHeader: "Brand",
    allowUserInput: true,
    ButtonType: "Radio",
    buttonValue: "Brand",
    arraylist: [
      { buttonText: `annabelle`, buttonValueText: "annabelle" },
      { buttonText: `benefit`, buttonValueText: "benefit" },
      { buttonText: `boosh`, buttonValueText: "boosh" },
      { buttonText: `almay`, buttonValueText: "almay" },
      { buttonText: `alva`, buttonValueText: "alva" },
      { buttonText: `clinique`, buttonValueText: "clinique" },
      { buttonText: `covergirl`, buttonValueText: "covergirl" },
      {
        buttonText: `coastal classic creation`,
        buttonValueText: "coastal classic creation",
      },
      { buttonText: `colourpop`, buttonValueText: "colourpop" },
      { buttonText: `dalish`, buttonValueText: "dalish" },
      { buttonText: `dior`, buttonValueText: "dior" },
      { buttonText: `dr.hauschka`, buttonValueText: "dr.hauschka" },
      { buttonText: `e.l.f.`, buttonValueText: "e.l.f." },
      { buttonText: `iman`, buttonValueText: "iman" },
      { buttonText: `l'oreal`, buttonValueText: "l'oreal" },
      { buttonText: `marcelle`, buttonValueText: "marcelle" },
      { buttonText: `maybelline`, buttonValueText: "maybelline" },
      { buttonText: `milani`, buttonValueText: "milani" },
      { buttonText: `mineral fusion`, buttonValueText: "mineral fusion" },
      { buttonText: `misa`, buttonValueText: "misa" },
      { buttonText: `mistura`, buttonValueText: "mistura" },
      { buttonText: `moov`, buttonValueText: "moov" },
      { buttonText: `nudus`, buttonValueText: "nudus" },
      { buttonText: `nyx`, buttonValueText: "nyx" },
      { buttonText: `orly`, buttonValueText: "orly" },
      { buttonText: `pacifica`, buttonValueText: "pacifica" },
      {
        buttonText: `penny lane organics`,
        buttonValueText: "penny lane organics",
      },
      {
        buttonText: `physicians formula`,
        buttonValueText: "physicians formula",
      },
      { buttonText: `piggy paint`, buttonValueText: "piggy paint" },
      { buttonText: `pure anada`, buttonValueText: "pure anada" },
      { buttonText: `revlon`, buttonValueText: "revlon" },
      { buttonText: `rejuva minerals`, buttonValueText: "rejuva minerals" },
      {
        buttonText: `sally b's skin yummies`,
        buttonValueText: "sally b's skin yummies",
      },
      { buttonText: `salon perfect`, buttonValueText: "salon perfect" },
      { buttonText: `sante`, buttonValueText: "sante" },
      { buttonText: `sinful colours`, buttonValueText: "sinful colours" },
      { buttonText: `smashbox`, buttonValueText: "smashbox" },
      { buttonText: `stila`, buttonValueText: "stila" },
      { buttonText: `suncoat`, buttonValueText: "suncoat" },
      { buttonText: `w3llpeople`, buttonValueText: "w3llpeople" },
      { buttonText: `wet n wild`, buttonValueText: "wet n wild" },
      { buttonText: `zorah`, buttonValueText: "zorah" },
      {
        buttonText: `zorah biocosmetiques`,
        buttonValueText: "zorah biocosmetiques",
      },
      { buttonText: `Remove All`, buttonValueText: "" },
    ],
  },
  {
    asideTextHeader: "Price",
    allowUserInput: true,
    ButtonType: "Radio",
    buttonValue: "Price",
    arraylist: [
      { buttonText: `Under $10`, buttonValueText: 10 },
      { buttonText: `Under $20`, buttonValueText: 20 },
      { buttonText: `Under $50`, buttonValueText: 50 },
      { buttonText: `Under $75`, buttonValueText: 75 },
    ],
  },
  {
    asideTextHeader: "Sort by Price",
    allowUserInput: false,
    ButtonType: "Radio",
    buttonValue: "Sort_By_Price",
    arraylist: [
      { buttonText: `Price: High to Low`, buttonValueText: "false" },
      { buttonText: `Price: Low to High`, buttonValueText: "true" },
    ],
  },

  {
    asideTextHeader: "Sort by Rating",
    allowUserInput: false,
    ButtonType: "Radio",
    buttonValue: "Sort_By_Rating",
    arraylist: [
      { buttonText: `1 Stars`, buttonValueText: 1 },
      { buttonText: `2 Stars`, buttonValueText: 2 },
      { buttonText: `3 Stars`, buttonValueText: 3 },
      { buttonText: `4 Stars`, buttonValueText: 4 },
    ],
  },
  {
    asideTextHeader: "Sort By Product Tags",
    allowUserInput: false,
    ButtonType: false,
    buttonValue: "Sort_By_Tags",
    arraylist: [
      { buttonText: `Canadian`, buttonValueText: "Canadian" },
      { buttonText: `CertClean`, buttonValueText: "CertClean" },
      { buttonText: `Chemical Free`, buttonValueText: "Chemical Free" },
      { buttonText: `EWG Verified`, buttonValueText: "EWG Verified" },
      { buttonText: `EcoCert`, buttonValueText: "EcoCert" },
      { buttonText: `Gluten Free`, buttonValueText: "Gluten Free" },
      { buttonText: `Fair Trade`, buttonValueText: "Fair Trade" },
      { buttonText: `Hypoallergenic`, buttonValueText: "Hypoallergenic" },
      { buttonText: `Natural`, buttonValueText: "Natural" },
      { buttonText: `No Talc`, buttonValueText: "No Talc" },
      { buttonText: `Non-GMO`, buttonValueText: "Non-GMO" },
      { buttonText: `Organic`, buttonValueText: "Organic" },
      {
        buttonText: `Peanut Free Product`,
        buttonValueText: "Peanut Free Product",
      },
      { buttonText: `Sugar Free`, buttonValueText: "Sugar Free" },
      { buttonText: `USDA Organic`, buttonValueText: "USDA Organic" },
      { buttonText: `Vegan`, buttonValueText: "Vegan" },
      { buttonText: `alcohol free`, buttonValueText: "alcohol free" },
      { buttonText: `cruelty free`, buttonValueText: "cruelty free" },
      { buttonText: `oil free`, buttonValueText: "oil free" },
      { buttonText: `purpicks`, buttonValueText: "purpicks" },
      { buttonText: `water free`, buttonValueText: "water free" },
      { buttonText: `silicone free`, buttonValueText: "silicone free" },
      { buttonText: `Remove All`, buttonValueText: "" },
    ],
  },
];
